name: Build & Merge Dist Artifacts

on:
  workflow_dispatch:  # allows you to launch the workflow manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the current branch
      - name: Checkout code
        uses: actions/checkout@v3

      # Environment setup
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Installing dependencies and the latest version of the standard library
      - name: Install dependencies
        run: |       
          npm install                          
          npm update @bsi-cx/design-standard-library-web      

      # Buld project
      - name: Build project
        run: |
          npm run build:prod

      # Upload all ZIPs of dist folder 
      - name: Upload Combined Artifact
        uses: actions/upload-artifact@v4
        with:
          name: master-template-web-all-builds
          path: dist/**/*.zip
